In [3]:
import torch 
print(torch.__version__) 



2.10.0+cpu


In [4]:
if torch.cuda.is_available : 
    print("GPU is available") 
else : 
    print("GPU is not available")


GPU is available


# what is PyTorch ? and Why do we need this ? 

Pytorch is a tool(library) used to build and train machine learning and deep learning models

without PyTorch 

- we have to do everything manually 
- matrix operations and slow and complex
- finding gradients is hard

with pytorch : 

- pytorch do the math automatically 
- handles gradients 
- works fast (uses gpu , cpu) 



## What are the tensors? 

Tensors are n dimentional array 

### 0-D tensor : actually scaler 
eg. : 0 
1 
4

### 1-D tensor : vectors 

eg. [2,4,6] 

used let say one row of [iq , cgpa , state] 

it is 1-D tensor but the dimension of the vector is 3 (becoz 3 elements are there)


### 2-D tensor : matrix 
eg. [
    [2,4,5],
    [7,4,3]
]

shape : (2,3) == (row , column)

used : 
if there is 1000 rows in the dataset of students of iq | cgpa | state | placed
for inputs there is 1000 vectors of [iq , cgpa , state]

### 3-D tensor : (3rd order tensor)
 [[
    [2,3,5] ,
    [5,4,1]
] , [
    [7,2,3],
    [9,8,7]
]]

example : time series data of stock 

higest | lowest 

365 days and 10 years 

(10 , 365 , 2) 

### 4-D tensors 

R G B layers , 50 images

(50,3,255,255)

### 5-D tensors 

videos in 30fps for 60 second

(60 , 30 , 3 , 255, 255)

## Creating Tensors

In [5]:
import torch 

a = torch.Tensor([2,1,5]) 

print(a) 

tensor([2., 1., 5.])


In [6]:

z = torch.zeros(2,3) 

print(z)  

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
one = torch.ones(4,3) 
print(one) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [8]:
temp = torch.rand(2,3) 

print(temp)

tensor([[0.5250, 0.7525, 0.7008],
        [0.8575, 0.4771, 0.9306]])


In [9]:
b = torch.arange(1,6) 
print(b)

tensor([1, 2, 3, 4, 5])


In [10]:
x = torch.Tensor([[2,3] , [6,7]]) 

print(x.shape) 

torch.Size([2, 2])


### Operations

In [11]:
ran1 = torch.rand(3,4) 
ran2 = torch.rand(3,4) 

print(ran1) 
print(ran2)

tensor([[0.4107, 0.9941, 0.4527, 0.8782],
        [0.5643, 0.5314, 0.3002, 0.9855],
        [0.4099, 0.3431, 0.1258, 0.7097]])
tensor([[0.5872, 0.1528, 0.6110, 0.6445],
        [0.6989, 0.2197, 0.2407, 0.8447],
        [0.8314, 0.2016, 0.7600, 0.1543]])


In [12]:
# addition 
print(ran1+ran2) 

# substraction
#division
#multiplication



tensor([[0.9979, 1.1469, 1.0637, 1.5227],
        [1.2631, 0.7511, 0.5409, 1.8302],
        [1.2414, 0.5447, 0.8858, 0.8640]])


In [13]:
# matrix multiplication 

x = torch.rand(3,4)*10 
y = torch.rand(4,4) *10 

c = torch.matmul(x,y) 

print(c)


tensor([[ 81.6202,  99.2811,  77.4448,  42.3094],
        [ 92.9963, 136.6557, 113.2624,  71.1911],
        [ 31.9691,  35.5045,  27.2691,  12.8456]])


In [14]:
# indexing 

x = torch.Tensor([1,2,3,4,5,6])

print(x[4])

## 2D indexing 

x = torch.Tensor([[2,3,4], [4,5,6]]) 



print(x[0][2]) # from [2,3,4] take 2nd element  /(0th,1st,2nd)/ 

tensor(5.)
tensor(4.)


In [15]:
# dot product 

x = torch.Tensor([1,2,4,5]) 
y = torch.Tensor([4,5,6,7])

c = torch.dot(x,y) 
print(c) 


tensor(73.)


In [16]:
#determinant 

u = torch.rand(3,3) * 10 

print(torch.det(u))

tensor(232.1942)


## Special Functions

In [22]:
k = torch.randint(size=(3,3),low=0,high=10, dtype=float) 

In [18]:
#log

torch.log(k) 

tensor([[1.6094,   -inf, 1.7918],
        [1.0986, 0.6931, 1.9459],
        [0.0000, 0.6931, 2.1972]])

In [20]:
#exp
torch.exp(k) 

tensor([[1.4841e+02, 1.0000e+00, 4.0343e+02],
        [2.0086e+01, 7.3891e+00, 1.0966e+03],
        [2.7183e+00, 7.3891e+00, 8.1031e+03]])

In [21]:
#sqrt

torch.sqrt(k)

tensor([[2.2361, 0.0000, 2.4495],
        [1.7321, 1.4142, 2.6458],
        [1.0000, 1.4142, 3.0000]])

In [24]:
#sigmoid

torch.sigmoid(k)

tensor([[0.9991, 0.9526, 0.9997],
        [0.8808, 0.8808, 0.5000],
        [0.8808, 0.8808, 0.5000]], dtype=torch.float64)

In [ ]:
#softmax

# relu

In [28]:
#Inplace Operation 


## NOT IN-PLACE
x = torch.Tensor([1,2,3]) 

y = x + 1 

print(x) 
print(y)

## IN-PLACE


torch.sqrt_(x)

print(x) 


# functions ending with underscore (_)  are in place mean less memory use 
# disadvange in autograd  because pytorch in original values for backprop

# add_() , mul_() 



tensor([1., 2., 3.])
tensor([2., 3., 4.])
tensor([1.0000, 1.4142, 1.7321])


In [37]:
## Reshape 

a = torch.randint(size=(4,4) , low=1 , high=10) 

b = a.reshape(4,2,2) 

print(b) 

## flatten 

c = a.flatten()
print(c)


## Unsqueeze use to add new dimension


x = torch.Tensor([1,2,3])

y = x.unsqueeze(0) 
print(y)

z = x.unsqueeze(1)

print(z)

## Permute 
# used to rearrage dimension 

n = torch.randn(2,3,4) 
y = n.permute(1,0,2) 

# shape change from (2,3,4) -> (3,2,4)


## Numpy to Tensor 

import numpy as np 

arr = np.array([1,2,3]) 

x = torch.from_numpy(arr) 

print(x) 

## tensor to numpy 

arr = x.numpy() 

print(arr)



tensor([[[5, 2],
         [7, 3]],

        [[6, 7],
         [1, 4]],

        [[9, 7],
         [8, 7]],

        [[4, 5],
         [2, 4]]])
tensor([5, 2, 7, 3, 6, 7, 1, 4, 9, 7, 8, 7, 4, 5, 2, 4])
tensor([[1., 2., 3.]])
tensor([[1.],
        [2.],
        [3.]])
tensor([1, 2, 3])
[1 2 3]
